### ISSUE TITLE
Multiple asset import issues

### ISSUE THREAD

**Issue by ibardash** [contentstack/cli#1677]
# Issue(s)

Import tool does not process the data produced by the export tool correctly (in my case, when importing assets). After my investigation it looks like there are multiple problems with it and fixing either of them doesn't make it possible to use the tool, hence a single issue to cover them all.

# Description

## Issue 1:
**The export tool saves the assets split into batches, however the import tool attempts creating batches as well.**

The export tool creates the following folder structure:
```
- export-data-destination
  - logs
  - main
    - assets
    - files
    - [uuid1]-assets.json
    - [uuid2]-assets.json
    - assets.json
    - folders.json
    - metadata.json
  - branches.json
```

The `assets.json` file is an index that contains the references to all batch files, e.g.:
```
{
    "1": "uuid1-assets.json",
    "2": "uuid2-assets.json"
}
```
However, [here](https://github.com/contentstack/cli/blob/8d59fa0c37a47e255f284c38489700428d0a7d13/packages/contentstack-import/src/import/modules-js/assets.js#L67-L72) the import tool expects to receive a flat file structure and splits the assets into batches. 

Running the import utility produces the following errors:
```
error: '[project-path]_backup_218/assets/files/1' does not exist!
info: Completed asset import of batch no: 1
error: [project-path]/_backup_218/assets/files/2' does not exist!
info: Completed asset import of batch no: 2
```

Replacing the highlighted lines of code with the following fixes this issue.
```
const batchesCompleteData = Object.values(self.assets).map(batchFilename => fileHelper.readFileSync(path.join(sanitizePath(self.assetsFolderPath), sanitizePath(batchFilename))));
self.assets = batchesCompleteData.flat().reduce((obj, item) => ({...obj, ...item}), {});
const batches = batchesCompleteData.map(assetList => Object.keys(assetList));
```

## Issue 2:
**The import tool references incorrect asset path.**

The files, when exported from a Contentstack's stack using the export tool, are nested under the `files` folder. 
[Here](https://github.com/contentstack/cli/blob/8d59fa0c37a47e255f284c38489700428d0a7d13/packages/contentstack-import/src/import/modules-js/assets.js#L95), however, the asset path does not include the `files` subfolder. 

## Issue 3:
I believe this is not strictly an import issue, but a broader problem - the file names  that include brackets (e.g. `filename (1).jpeg`) [are considered invalid](https://github.com/contentstack/cli/blob/8d59fa0c37a47e255f284c38489700428d0a7d13/packages/contentstack-utilities/src/helpers.ts#L62). Contentstack's web interface allows this format and I think it's fairly common to have brackets in file names in general (for example when a file is copied), so I think it's a bug.

# Tool Versions & commands

Tried using two versions of the cli:
- v1.17.5
- v1.29.0

Tried two Node versions:
- v18.19.0
- v21.0.0

The command used for import:
`csdx cm:stacks:import -a management-token -d "./scripts/migrate/import/main" --module assets --branch main`

**Comment by cs-raj** [comment]
Hi @ibardash we have taken the issues and we are looking into it we will share the update.

**Comment by aman19K** [comment]
Hi @ibardash ,

It appears that the `export-info` file is missing. It's possible that the `export-info.json` file was accidentally deleted from the data directory.

The export tool creates the following folder structure:

```
- export-data-destination
  - logs
  - main
    - assets
    - files
    - [uuid1]-assets.json
    - [uuid2]-assets.json
    - assets.json
    - folders.json
    - metadata.json
  - branches.json
  - export-info.json
```

The `export-info.json` file contains version information that helps determine whether to use the latest TypeScript (TS) code or the older JavaScript (JS) code. If the file is missing, the system defaults to using the older version (JS). 

- Latest TS code:[ TS Modules](https://github.com/contentstack/cli/tree/main/packages/contentstack-import/src/import/modules)
- Legacy JS code (no longer maintained): [JS Modules](https://github.com/contentstack/cli/tree/main/packages/contentstack-import/src/import/modules-js)

### Issue 1:
When running the import utility, the following errors occur:

```
error: '[project-path]_backup_218/assets/files/1' does not exist!
info: Completed asset import of batch no: 1
error: '[project-path]_backup_218/assets/files/2' does not exist!
info: Completed asset import of batch no: 2
```

The missing `export-info` file causes the system to default to the older JS code. However, in the latest TS code, the asset file structure has changed, which is why you're encountering these errors.

### Issue 2:
Since the `export-info` file is missing, the import utility is using the older JS code. In the latest TS code, we've made updates to handle this issue.

### Issue 3:
In the latest asset import module, this validation is no longer being used. We've tested it, and it's working as expected.

Please check for the missing `export-info.json` file. The issues you're experiencing are related to this missing file.

CC: @netrajpatel @shafeeqd959 @cs-raj

**Comment by ibardash** [comment]
Hi @aman19K , thanks for your reply!

I checked my export directory and I do have the export info file, however it is nested under the `main` subfolder (the name of the branch), whereas in your referenced structure it's in the root. I haven't done any modifications to the data.

**Comment by aman19K** [comment]
@ibardash , It should be nested under the main subfolder. Your data structure appears to be accurate. I apologise for any confusion; I have corrected the structure in the comment above. Could you look at the export-info file? It should contain contentVersion: 2.

**Comment by ibardash** [comment]
Yeah the content version is set to 2, so it should be correct.

Is there a way to explicitly specify which version should be used by the import/export utilities apart from having this file?

**Comment by ibardash** [comment]
Thanks @aman19K 
Happy to close the ticket if all tests pass on your end and you don't see the issue. I've already migrated the content over two weeks ago with the fixes I listed so I don't think investigating this further would be necessary.
